name: IDS-Push-CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        id: node-cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            node-modules-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
      - uses: pnpm/action-setup@v4

      - name: Install Dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: |
          pnpm install --shamefully-hoist

      - name: Jest Integration Test
        run: |
          pnpm run test --passWithNoTests

      - name: Build
        run: |
          pnpm build

      - name: NPM publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
