name: IDS-Pull-Request-CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Cache node modules
      id: node-cache
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: node_modules-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          node-modules-

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: |
        pnpm install

    - name: Build
      run: |
        pnpm build
        
    - name: Build:StoryBook
      run: |
        pnpm build-storybook
        
    - name: Prettier Format Check
      run: |
        pnpm run prettier
        
    - name: Lint Format Check
      run: |
        pnpm run eslint
        
    - name: Jest Integration Test
      run: |
        pnpm test --passWithNoTests